-- MySQL Script generated by MySQL Workbench
-- Tue May 21 19:09:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Immobilien
-- -----------------------------------------------------
-- 
-- 
-- 
-- 
-- 

-- -----------------------------------------------------
-- Schema Immobilien
--
-- 
-- 
-- 
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Immobilien` DEFAULT CHARACTER SET utf8 ;
USE `Immobilien` ;

-- -----------------------------------------------------
-- Table `Immobilien`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`Address` (
  `Postal_code_id` INT NOT NULL,
  `ort` VARCHAR(45) NOT NULL,
  `hausnummer` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Postal_code_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`User` (
  `persnr_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `second name` VARCHAR(45) NOT NULL,
  `date of birth` DATETIME NOT NULL,
  `postal_code` INT NOT NULL,
  PRIMARY KEY (`persnr_id`),
  UNIQUE INDEX `Persnr_UNIQUE` (`persnr_id` ASC),
  INDEX `Postal_code_id_idx` (`postal_code` ASC),
  CONSTRAINT `postal_code`
    FOREIGN KEY (`postal_code`)
    REFERENCES `Immobilien`.`Address` (`Postal_code_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`Contract` (
  `contract_id` INT NOT NULL AUTO_INCREMENT,
  `caution` DOUBLE NOT NULL,
  `rent_Amount` DOUBLE NOT NULL,
  `contract_date` DATETIME NOT NULL,
  `payment_date_rent` DATETIME NOT NULL,
  `renter` INT NOT NULL,
  `house_owner` INT NOT NULL,
  PRIMARY KEY (`contract_id`),
  UNIQUE INDEX `contract_id_UNIQUE` (`contract_id` ASC),
  INDEX `renter_idx` (`renter` ASC),
  INDEX `house_owner_idx` (`house_owner` ASC),
  CONSTRAINT `renter`
    FOREIGN KEY (`renter`)
    REFERENCES `Immobilien`.`User` (`persnr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `house_owner`
    FOREIGN KEY (`house_owner`)
    REFERENCES `Immobilien`.`User` (`persnr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`Account` (
  `Account_id` INT NOT NULL AUTO_INCREMENT,
  `opening_Acc_date` DATETIME NOT NULL,
  `account_onwer` INT NOT NULL,
  PRIMARY KEY (`Account_id`),
  UNIQUE INDEX `Account_id_UNIQUE` (`Account_id` ASC),
  INDEX `Account_onwer_idx` (`account_onwer` ASC),
  CONSTRAINT `account_onwer`
    FOREIGN KEY (`account_onwer`)
    REFERENCES `Immobilien`.`User` (`persnr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`Accomodation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`Accomodation` (
  `Accomodation_id` INT PRIMARY KEY AUTO_INCREMENT,
  `comment` VARCHAR(45) NULL,
  `livingsurface` DOUBLE NOT NULL,
  `layoutplan` BLOB NULL,
  `buildingplan` BLOB NULL,
  `postal_code` INT NOT NULL
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`Payment` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_date` DATETIME NULL,
  `account_number` INT NOT NULL,
  `contract_number` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC),
  INDEX `account_id_idx` (`account_number` ASC),
  INDEX `contract_number_idx` (`contract_number` ASC),
  CONSTRAINT `account_number`
    FOREIGN KEY (`account_number`)
    REFERENCES `Immobilien`.`Account` (`Account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contract_number`
    FOREIGN KEY (`contract_number`)
    REFERENCES `Immobilien`.`Contract` (`contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`Firealarm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`Firealarm` (
  `Firealarm_id` INT NOT NULL,
  `installation_date` DATETIME NOT NULL,
  `place_of_installation` VARCHAR(45) NOT NULL,
  `accomodation_id` INT NOT NULL,
  `installator` INT NOT NULL,
  PRIMARY KEY (`Firealarm_id`),
  UNIQUE INDEX `Firealarm_id_UNIQUE` (`Firealarm_id` ASC),
  INDEX `accomodation_id_idx` (`accomodation_id` ASC),
  INDEX `installator_idx` (`installator` ASC),
  CONSTRAINT `accomodation_id`
    FOREIGN KEY (`accomodation_id`)
    REFERENCES `Immobilien`.`Accomodation` (`Accomodation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `installator`
    FOREIGN KEY (`installator`)
    REFERENCES `Immobilien`.`User` (`persnr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`Renovation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`Renovation` (
  `renovation_id` INT NOT NULL AUTO_INCREMENT,
  `worker_name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(45) NULL,
  `supervisor` INT NOT NULL,
  PRIMARY KEY (`renovation_id`),
  UNIQUE INDEX `renovation_id_UNIQUE` (`renovation_id` ASC),
  INDEX `supervisor_idx` (`supervisor` ASC),
  CONSTRAINT `supervisor`
    FOREIGN KEY (`supervisor`)
    REFERENCES `Immobilien`.`User` (`persnr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`Handcraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`Handcraft` (
  `handcraft_id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(45) NULL,
  `supervisor` INT NOT NULL,
  PRIMARY KEY (`handcraft_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`DistributionKey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`DistributionKey` (
  `distributionKey_id` INT NOT NULL,
  `wastecharge` INT NULL DEFAULT 0,
  `elevator` INT NULL DEFAULT 0,
  `administrativeCharges` INT NULL DEFAULT 0,
  `propertyportion` INT NULL DEFAULT 0,
  `accomodation_id` INT NOT NULL,
  `charge_id` INT NOT NULL,
  PRIMARY KEY (`distributionKey_id`))

ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Immobilien`.`Charge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`Charge` (
  `Charge_id` INT NOT NULL,
  `waste_disposal` DOUBLE NULL DEFAULT 0,
  `street_cleaning` DOUBLE NULL DEFAULT 0,
  `liability_insurance` DOUBLE NULL DEFAULT 0,
  `caretaker` DOUBLE NULL,
  `staircase_cleaning` DOUBLE NULL DEFAULT 0,
  `TÜV_elavator` DOUBLE NULL DEFAULT 0,
  `electricity` DOUBLE NULL DEFAULT 0,
  `administration_cost` DOUBLE NULL DEFAULT 0,
  `accomodation_id` INT NOT NULL,
  `distributionkey` INT NOT NULL,
  PRIMARY KEY (`Charge_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`NotificationProblem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`NotificationProblem` (
  `NotificationProblem_id` INT NOT NULL AUTO_INCREMENT,
  `problem_description` VARCHAR(500) NULL,
  `nodification_date` DATETIME NULL,
  `image` BLOB NULL,
  `renter` INT NOT NULL,
  `caretaker` INT NOT NULL,
  PRIMARY KEY (`NotificationProblem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`HandcraftDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`HandcraftDetail` (
  `accomodation_id` INT NOT NULL,
  `handcraft_id` INT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`accomodation_id`, `handcraft_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`RenovationDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`RenovationDetail` (
  `RenovationDetail_id` INT NOT NULL,
  `acccomodation_id` INT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`RenovationDetail_id`, `acccomodation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`accomdationdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`accomdationdetails` (
  `accomdation_number` INT NOT NULL,
  `caretaker` INT NOT NULL,
  `proprietor` INT NOT NULL,
  PRIMARY KEY (`accomdation_number`, `caretaker`, `proprietor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immobilien`.`ContractDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immobilien`.`ContractDetail` (
  `accomodation_number` INT NOT NULL,
  `contract_number` INT NOT NULL,
  PRIMARY KEY (`accomodation_number`, `contract_number`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
